@startuml
title Standart Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(client, "Client", "A client of the standart bank")
Person(worker, "Worker", "A worker of the standart bank")
Person(callcenterman, "CallCenterMan", "A worker of the ext call center")
 
System(StandartBankSystem, "Standart Bank System", "Bank functionality deposit and credits")

System_Ext(ExtCallCenter, "Ext call center system", "External call center system")

Rel(client, StandartBankSystem, "Uses the system")
Rel(worker,StandartBankSystem, "Work with system")
Rel(callcenterman,client, "Support")
Rel(callcenterman,ExtCallCenter,"Work with system")
@enduml
